
FROM python:3-alpine
RUN pip3 install mkdocs mkdocs-material
ENV app /app
RUN mkdir $app
WORKDIR $app
ADD . $app
RUN mkdocs build && mv site public-html


FROM httpd:latest
WORKDIR /root/
COPY --from=0 /app/public-html /usr/local/apache2/htdocs/
EXPOSE 80
