# Project information
site_name: Container Workload Insights
site_description: Insights about the the APPUiO workload
site_url: https://github.com/vshn/container-workload-insights

# Repository
repo_name: Container Workload Insights
repo_url: https://github.com/vshn/container-workload-insights


theme:
    name: material
    language: en

# Disable edit uri to get a cleaner view
edit_uri: ''

extra:
    social:
        - { type: 'github', link: 'https://github.com/vshn/container-workload-insights' }

extra_css:
    - css/extra.css

extra_javascript:
    - js/autoexpand.js

nav:
    - Welcome: index.md
    - Databases: databases.md
    - Programming Languages: languages.md
    - Web Servers: webservers.md

